<?php
/** @var $block \Magento\Catalog\Block\Product\View */
$callPriceHelper = $this->helper('Darsh\Callforprice\Helper\Data');
$buttonTitle = $callPriceHelper->getButtonTitle();
?>
<?php $_product = $block->getProduct(); ?>
<?php $callForPrice = $callPriceHelper->showCallForPriceButton($_product); ?>
<!--call for price condition-->
<!-- <?php //echo $callForPrice; die(); ?> -->
<?php if ($callForPrice == 0 || $callPriceHelper->isEnable() == 0) { ?>
    <?php $buttonTitle = __('Add to Cart');
     ?>
    <?php if ($_product->isSaleable()): ?>
        <div class="box-tocart">
            <div class="fieldset">
                <?php if ($block->shouldRenderQuantity()): ?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                        <div class="control">
                            <input type="number"
                                   name="qty"
                                   id="qty"
                                   maxlength="12"
                                   value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                                   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                                   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                            />
                        </div>
                    </div>
                <?php endif; ?>
                <div class="actions">
                    <button type="submit"
                            title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
            "radioCheckboxClosest": ".nested"
            }
            }
            }
        </script>
    <?php else : ?>
        <script>
            require([
                'jquery',
                'mage/mage',
                'Magento_Catalog/product/view/validation',
                'Magento_Catalog/js/catalog-add-to-cart'
            ], function ($) {
                'use strict';

                $('#product_addtocart_form').mage('validation', {
                    radioCheckboxClosest: '.nested',
                    submitHandler: function (form) {
                        var widget = $(form).catalogAddToCart({
                            bindSubmit: false
                        });

                        widget.catalogAddToCart('submitForm', $(form));

                        return false;
                    }
                });
            });
        </script>
    <?php endif; ?>

<?php }else { ?>
    <?php if ($_product->isSaleable()): ?>
        <div class="add-to-cart box-tocart">
            <button type="button" title="<?php echo $buttonTitle ?>" id="modalRun" class="action primary tocart modalRun"><span><span><?php echo $buttonTitle ?></span></span></button>
        </div>

        <div id="popup-modal">

        </div>
    <?php endif; ?>

<?php } ?>
