<?php
$_product = $block->getProduct();
$callPriceHelper = $this->helper('Darsh\Callforprice\Helper\Data');
$submitformurl = $callPriceHelper->submitformurl();
$customerData = $callPriceHelper->getCurrentCustomerData();
?>
<div id="modal-content">
    <div id="response-message"></div>
    <div class="modal-body">
        <form name="cp_form" id="cp_form" method="post" enctype="multipart/form-data" autocomplete="off" data-mage-init='{"validation":{}}' data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
            <fieldset class="fieldset">
                <div class="field name required">
                    <label class="label" for="customer_name"><span><?php echo __("Name"); ?></span></label>
                    <div class="control">
                        <input name="customer_name" id="customer_name" title="Name" value="<?php
                        if ($customerData) {
                            echo $customerData->getName();
                        }

                        ?>" class="input-text" type="text" data-validate="{required:true}" />
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="customer_email"><span><?php echo __("Email"); ?></span></label>
                    <div class="control">
                        <input name="customer_email" id="customer_email" title="Email" value="<?php
                        if ($customerData) {
                            echo $customerData->getEmail();
                        }

                        ?>" class="input-text" type="text" data-validate="{required:true, 'validate-email':true}" />
                    </div>
                </div>
                <div class="field telephone required">
                    <label class="label" for="customer_telephone"><span><?php echo __("Telephone"); ?></span></label>
                    <div class="control">
                        <input name="customer_telephone" id="customer_telephone" title="Telephone" value="" type="text" class="input-text" data-validate="{required:true}" />
                    </div>
                </div>
                <div class="field request_detail required">
                    <label class="label" for="request_detail"><span><?php echo __("Request Details"); ?></span></label>
                    <div class="control">
                        <textarea rows="3" cols="5" class="input-text" title="details" id="request_detail" name="request_detail" data-validate="{required:true}"><?php echo "Product Name = ".$_product->getName(); ?></textarea>
                    </div>
                </div>
            </fieldset>
            <input type="hidden" name="status" id="status" value="1"/>
            <input type="hidden" name="product_name" id="product_name" value="<?php echo $_product->getName(); ?>"/>
            <input type="hidden" name="product_id" id="product_id" value="<?php echo $_product->getEntityId(); ?>"/>
            <input type="hidden" name="customer_id" id="customer_id" value="<?php echo $_product->getEntityId(); ?>"/>
        </form>
    </div>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function ($, modal) {
            $('#modal-content').modal({
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: "Submit Form For Price",
                buttons: [{
                    text: $.mage.__('Submit'),
                    class: 'action  primary',
                    click: function (data) {
                        var dataForm = $('#cp_form');
                        if (dataForm.validation('isValid')) {
                            var customer_name = $("#customer_name").val();
                            var customer_email = $("#customer_email").val();
                            var customer_telephone = $("#customer_telephone").val();
                            var request_detail = $("#request_detail").val();
                            var product_id = $("#product_id").val();
                            var customer_id = $("#customer_id").val();
                            var status = $("#status").val();
                            var product_name = $("#product_name").val();
                            if (customer_name && customer_email && customer_telephone && request_detail && product_id && customer_id) {
                                $.ajax({
                                    url: "<?php echo $submitformurl; ?>",
                                    dataType: 'json',
                                    type: 'POST',
                                    showLoader: true,
                                    data: {customer_name: customer_name, customer_email: customer_email, customer_telephone: customer_telephone, request_detail: request_detail, product_id: product_id, customer_id: customer_id, status: status, product_name: product_name},
                                    success: function (data) {
                                        if (data.status == "success") {
                                            $("#cp_form").trigger("reset");
                                            $("#response-message").addClass("success");
                                            $("#response-message").html(data.message);
                                        } else {
                                            $("#response-message").addClass("error");
                                            $("#response-message").html(data.message);
                                        }
                                    }
                                });
                            }
                        }
                    }
                }]
            });
            $("#modalRun").on("click", function () {
                $("#cp_form").trigger("reset");
                $("#response-message").html("");
                $("#response-message").removeClass("success");
                $("#response-message").removeClass("error");
                $('#modal-content').modal('openModal');
            });
            $('.modal-popup').wrap('<div class="call-for-price"></div>')
        });

</script>
